registry:
  agents:
    mf:
      opencode:
        backend-designer:
          description: Backend designer (API, Architecture, Optimization, Scalability, Long Term)
          source: https://github.com/Marvino-Fransisco/agent-registry/blob/main/agents/opencode/backend-designer.md
          skills: [backend]
        data-designer:
          description: Data Designer (Modeling, Pipelines, Analytics, Governance, Long Term)
          source: https://github.com/Marvino-Fransisco/agent-registry/blob/main/agents/opencode/bdata-designer.md
          skills: [data-design]
        frontend-designer:
          description: Frontend designer (UI, Codes, Optimization, Scalability, Long Term)
          source: https://github.com/Marvino-Fransisco/agent-registry/blob/main/agents/opencode/bfrontend-designer.md
          skills: [frontend]
        researcher:
          description: Researcher (Technology, Architecture, Libraries, Tools, Trends, Deep Dives)
          source: https://github.com/Marvino-Fransisco/agent-registry/blob/main/agents/opencode/bresearcher.md
          skills: [research]
        software-engineer:
          description: Software Engineer (SOLID, Design Pattern, Architecture, Codes, Optimization, Scalability, Long Term)
          source: https://github.com/Marvino-Fransisco/agent-registry/blob/main/agents/opencode/bsoftware-engineer.md
          skills: [software-engineering]
      pi:
      claudecode:
  skills:
    mf:
      data-design:
        description: Use this skill when doing any data design, database, and data pipeline work
        source: https://github.com/Marvino-Fransisco/agent-registry/tree/main/skills/data-design
      research:
        description: Use this skill when doing any researches
        source: https://github.com/Marvino-Fransisco/agent-registry/tree/main/skills/research
      software-engineering:
        description: Use this skill when doing any programming and engineering work
        source: https://github.com/Marvino-Fransisco/agent-registry/tree/main/skills/software-engineering
      create-agent:
        description: "this skill is used to create new agent"
        source: https://github.com/Marvino-Fransisco/agent-registry/tree/main/skills/create-agent
      create-skill:
        source: https://github.com/Marvino-Fransisco/agent-registry/tree/main/skills/create-skill
        description: ""
      create-markdown:
        source: https://github.com/Marvino-Fransisco/agent-registry/tree/main/skills/create-markdown
        description: ""
